Repository Nexters/Funch-AOS, pull requests merged in 2024-02, with the labels that each got.

#30 [feat] UserCodeDataStore - userId 추가
  core/datastore/src/main/java/com/moya/funch/datastore/DefaultUserCodeDataStore.kt
  core/datastore/src/main/java/com/moya/funch/datastore/UserCodeDataStore.kt
Labels: june🙇‍♂️

#31 [Feat] FunchChip matched 시 border 및 neonSign 효과 구현
  core/designsystem/src/main/java/com/moya/funch/component/Button.kt
  core/designsystem/src/main/java/com/moya/funch/component/Chip.kt
  core/designsystem/src/main/java/com/moya/funch/modifier/NeonSign.kt
  core/designsystem/src/main/java/com/moya/funch/theme/Shape.kt
Labels: june🙇‍♂️

#32 [fix] profileResponse DTO 변경 - 별자리 out, 혈액형 on
  core/network/src/main/java/com/moya/funch/network/dto/response/profile/ProfileResponse.kt
  core/network/src/test/java/com/moya/funch/network/service/MatchingServiceTest.kt
  core/network/src/test/res/matching_result.json
Labels: june🙇‍♂️

#38 [Feature] data module 초기 세팅
  core/data/.gitignore
  core/data/build.gradle.kts
  core/data/src/main/java/com/moya/funch/datasource/DummyDataSource.kt
  core/data/src/main/java/com/moya/funch/datasource/local/DummyLocalDataSource.kt
  core/data/src/main/java/com/moya/funch/datasource/remote/DummyRemoteDataSource.kt
  core/data/src/main/java/com/moya/funch/di/DummyModule.kt
  core/data/src/main/java/com/moya/funch/mapper/DummyMapper.kt
  core/data/src/main/java/com/moya/funch/model/DummyModel.kt
  core/data/src/main/java/com/moya/funch/repository/DummyRepository.kt
  settings.gradle.kts
Labels: june🙇‍♂️

#33 [feat] domain module 세팅, matching profile entity 설정
  .github/pull_request_template.md
  core/domain/build.gradle.kts
  core/domain/src/main/java/com/moya/funch/entity/Blood.kt
  core/domain/src/main/java/com/moya/funch/entity/Club.kt
  core/domain/src/main/java/com/moya/funch/entity/Job.kt
  core/domain/src/main/java/com/moya/funch/entity/Mbti.kt
  core/domain/src/main/java/com/moya/funch/entity/SubwayStation.kt
  core/domain/src/main/java/com/moya/funch/entity/match/Chemistry.kt
  core/domain/src/main/java/com/moya/funch/entity/match/Matching.kt
  core/domain/src/main/java/com/moya/funch/entity/match/Recommend.kt
  core/domain/src/main/java/com/moya/funch/entity/profile/Profile.kt
  core/domain/src/main/java/com/moya/funch/repository/MatchingRepository.kt
  core/domain/src/main/java/com/moya/funch/usecase/MatchProfileUseCase.kt
  core/domain/src/test/java/com/moya/funch/entity/ClubTest.kt
  core/domain/src/test/java/com/moya/funch/entity/JobTest.kt
  settings.gradle.kts
Labels: june🙇‍♂️

#44 [Feat] Matching UI 구현 (Profile 부분 제외), statusBar Color 설정, Throttle 증가
  app/src/main/java/com/moya/funch/navigation/FunchNavHost.kt
  core/designsystem/src/main/java/com/moya/funch/component/Card.kt
  core/designsystem/src/main/java/com/moya/funch/component/TopBar.kt
  core/designsystem/src/main/java/com/moya/funch/modifier/ClickableSingle.kt
  core/designsystem/src/main/java/com/moya/funch/theme/Theme.kt
  core/designsystem/src/main/java/com/moya/funch/ui/FunchTopBar.kt
  core/domain/src/main/java/com/moya/funch/entity/match/Matching.kt
  feature/match/build.gradle.kts
  feature/match/src/main/java/com/moya/funch/match/MatchScreen.kt
  feature/match/src/main/java/com/moya/funch/match/MatchViewModel.kt
  feature/match/src/main/java/com/moya/funch/match/component/MatchCardLayout.kt
  feature/match/src/main/java/com/moya/funch/match/component/MatchHorizontalPager.kt
  feature/match/src/main/java/com/moya/funch/match/component/MatchPageIndicator.kt
  feature/match/src/main/java/com/moya/funch/match/component/MatchTopBar.kt
  feature/match/src/main/java/com/moya/funch/match/component/RecommendCardContent.kt
  feature/match/src/main/java/com/moya/funch/match/component/SimularityCardContent.kt
  feature/match/src/main/java/com/moya/funch/match/navigation/MatchNavigatoin.kt
  feature/match/src/main/java/com/moya/funch/match/theme/MatchColor.kt
Labels: june🙇‍♂️

#52 Feature/matching data
  core/data/src/main/java/com/moya/funch/datasource/remote/RemoteMatchDataSource.kt
  core/data/src/main/java/com/moya/funch/datasource/remote/RemoteMatchDataSourceImpl.kt
  core/data/src/main/java/com/moya/funch/di/DataSourcesModule.kt
  core/data/src/main/java/com/moya/funch/mapper/DummyMapper.kt
  core/data/src/main/java/com/moya/funch/mapper/MatchingMapper.kt
  core/data/src/main/java/com/moya/funch/repository/MatchingRepositoryImpl.kt
  core/domain/src/main/java/com/moya/funch/repository/MatchingRepository.kt
  core/domain/src/main/java/com/moya/funch/usecase/CanMatchProfileUseCase.kt
  core/domain/src/main/java/com/moya/funch/usecase/MatchProfileUseCase.kt
Labels: june🙇‍♂️

#54 Feature/home data domain logic
  core/data/src/main/java/com/moya/funch/repository/MemberRepositoryImpl.kt
  core/domain/src/main/java/com/moya/funch/repository/MemberRepository.kt
  core/domain/src/main/java/com/moya/funch/usecase/LoadViewCountUseCase.kt
Labels: june🙇‍♂️

#55 [fix] data모듈 Result.map() -> Result.mapCatching으로 수정, dataStore DeviceId : USER_ID -> DeviceID로 수정
  core/data/src/main/java/com/moya/funch/datasource/local/LocalUserDataSourceImpl.kt
  core/data/src/main/java/com/moya/funch/datasource/remote/RemoteMatchDataSourceImpl.kt
  core/data/src/main/java/com/moya/funch/datasource/remote/RemoteMemberDataSourceImpl.kt
  core/data/src/main/java/com/moya/funch/datasource/remote/RemoteUserDataSourceImpl.kt
  core/data/src/main/java/com/moya/funch/repository/MatchingRepositoryImpl.kt
  core/data/src/main/java/com/moya/funch/repository/MemberRepositoryImpl.kt
  core/datastore/src/main/java/com/moya/funch/datastore/UserDataStoreImpl.kt
  core/domain/src/main/java/com/moya/funch/usecase/CanMatchProfileUseCase.kt
Labels: june🙇‍♂️

#57 [Feature] OnBoarding UI 구현, APP Icon 추가
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/ic_funch_logo-playstore.png
  app/src/main/res/drawable/ic_app_icon.xml
  app/src/main/res/drawable/ic_funch_logo_foreground.xml
  app/src/main/res/mipmap-anydpi-v26/ic_funch_logo.xml
  app/src/main/res/mipmap-anydpi-v26/ic_funch_logo_round.xml
  app/src/main/res/mipmap-hdpi/ic_funch_logo.webp
  app/src/main/res/mipmap-hdpi/ic_funch_logo_round.webp
  app/src/main/res/mipmap-mdpi/ic_funch_logo.webp
  app/src/main/res/mipmap-mdpi/ic_funch_logo_round.webp
  app/src/main/res/mipmap-xhdpi/ic_funch_logo.webp
  app/src/main/res/mipmap-xhdpi/ic_funch_logo_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_funch_logo.webp
  app/src/main/res/mipmap-xxhdpi/ic_funch_logo_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_funch_logo.webp
  app/src/main/res/mipmap-xxxhdpi/ic_funch_logo_round.webp
  app/src/main/res/values/ic_funch_logo_background.xml
  app/src/main/res/values/strings.xml
  feature/home/src/main/java/com/moya/funch/theme/HomeColors.kt
  feature/match/src/main/java/com/moya/funch/MatchScreen.kt
  feature/match/src/main/java/com/moya/funch/MatchViewModel.kt
  feature/match/src/main/java/com/moya/funch/navigation/MatchNavigatoin.kt
  feature/onboarding/.gitignore
  feature/onboarding/build.gradle.kts
  feature/onboarding/proguard-rules.pro
  feature/onboarding/src/main/AndroidManifest.xml
  feature/onboarding/src/main/java/com/moya/funch/onboarding/OnBoardingScreen.kt
  feature/onboarding/src/main/java/com/moya/funch/onboarding/navigation/OnBoardingNavigation.kt
  feature/onboarding/src/main/java/com/moya/funch/onboarding/theme/OnBoardingColors.kt
  feature/onboarding/src/main/res/raw/temp_lottie.json
  feature/onboarding/src/main/res/values/strings.xml
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: june🙇‍♂️

#59 [Feat] match 화면 icon 적용, Usecase 적용
  core/data/src/main/java/com/moya/funch/datasource/remote/RemoteMatchDataSourceImpl.kt
  core/data/src/main/java/com/moya/funch/mapper/MatchingMapper.kt
  core/network/src/main/java/com/moya/funch/network/dto/response/match/ProfileResponse.kt
  core/network/src/test/java/com/moya/funch/network/service/MatchingServiceTest.kt
  feature/home/src/main/res/values/strings.xml
  feature/match/src/main/java/com/moya/funch/match/MatchScreen.kt
  feature/match/src/main/java/com/moya/funch/match/MatchViewModel.kt
  feature/match/src/main/java/com/moya/funch/match/component/MatchHorizontalPager.kt
  feature/match/src/main/java/com/moya/funch/match/component/SimularityCardContent.kt
  feature/match/src/main/res/values/strings.xml
Labels: june🙇‍♂️

#58 [Feat] 프로필 생성 UI 제작
  app/src/main/AndroidManifest.xml
  core/designsystem/src/main/java/com/moya/funch/common/SearchPainter.kt
  core/designsystem/src/main/java/com/moya/funch/component/Button.kt
  core/designsystem/src/main/java/com/moya/funch/component/Label.kt
  core/designsystem/src/main/java/com/moya/funch/component/TextField.kt
  core/designsystem/src/main/java/com/moya/funch/ui/FunchFeedbackButton.kt
  core/designsystem/src/main/res/drawable/ic_designer_18.png
  core/designsystem/src/main/res/drawable/ic_designer_18.xml
  core/designsystem/src/main/res/drawable/ic_developer_18.png
  core/designsystem/src/main/res/drawable/ic_developer_18.xml
  core/domain/src/main/java/com/moya/funch/entity/Blood.kt
  core/domain/src/main/java/com/moya/funch/entity/profile/Profile.kt
  feature/profile/src/main/java/com/moya/funch/CreatePofileViewModel.kt
  feature/profile/src/main/java/com/moya/funch/CreateProflieScreen.kt
  feature/profile/src/main/java/com/moya/funch/MyProfileScreen.kt
  feature/profile/src/main/java/com/moya/funch/navigation/MyProfileNavigatoin.kt
  feature/profile/src/main/java/com/moya/funch/uimodel/MbtiItem.kt
  feature/profile/src/main/java/com/moya/funch/uimodel/ProfileLabel.kt
  feature/profile/src/main/res/values/strings.xml
Labels: ham😸

#69 [Feature] onboarding lottie -> Icon 으로 바꾸기, dummyId -> dataStore.id로 바꾸기
  core/data/src/main/java/com/moya/funch/datasource/remote/RemoteMatchDataSourceImpl.kt
  feature/onboarding/src/main/java/com/moya/funch/onboarding/OnBoardingScreen.kt
  feature/onboarding/src/main/res/drawable/onboarding.xml
  feature/onboarding/src/main/res/raw/temp_lottie.json
Labels: june🙇‍♂️

#70 [Feature] 매칭시 발생되는 로딩 UI 구현 및 적용
  feature/match/build.gradle.kts
  feature/match/src/main/java/com/moya/funch/match/MatchScreen.kt
  feature/match/src/main/java/com/moya/funch/match/MatchViewModel.kt
  feature/match/src/main/res/raw/funch_character_loading.json
  feature/match/src/main/res/values/strings.xml
Labels: ham😸

#71 [fix] 앱 로고 수정
  app/src/main/ic_funch_logo-playstore.png
  app/src/main/res/drawable/ic_funch_logo_foreground.xml
  app/src/main/res/mipmap-hdpi/ic_funch_logo.webp
  app/src/main/res/mipmap-hdpi/ic_funch_logo_round.webp
  app/src/main/res/mipmap-mdpi/ic_funch_logo.webp
  app/src/main/res/mipmap-mdpi/ic_funch_logo_round.webp
  app/src/main/res/mipmap-xhdpi/ic_funch_logo.webp
  app/src/main/res/mipmap-xhdpi/ic_funch_logo_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_funch_logo.webp
  app/src/main/res/mipmap-xxhdpi/ic_funch_logo_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_funch_logo.webp
  app/src/main/res/mipmap-xxxhdpi/ic_funch_logo_round.webp
Labels: june🙇‍♂️

#68 [Feat] 내 프로필 기능 구현
  core/data/src/main/java/com/moya/funch/datasource/local/LocalUserDataSourceImpl.kt
  core/designsystem/src/main/java/com/moya/funch/common/SearchPainter.kt
  core/domain/src/main/java/com/moya/funch/entity/SubwayStation.kt
  core/domain/src/main/java/com/moya/funch/entity/profile/Profile.kt
  feature/profile/src/main/java/com/moya/funch/MyProfileScreen.kt
  feature/profile/src/main/java/com/moya/funch/MyProfileViewModel.kt
Labels: ham😸

#74 [feat] 피드백 버튼에 구글 폼 연동
  core/designsystem/src/main/java/com/moya/funch/ui/FunchFeedbackButton.kt
Labels: june🙇‍♂️

#72 [Feat] 지하철 검색 기능 Data, Domain, Network 구현
  app/src/main/java/com/moya/funch/di/SubwayModule.kt
  core/data/src/main/java/com/moya/funch/datasource/remote/RemoteSubwayDataSource.kt
  core/data/src/main/java/com/moya/funch/datasource/remote/RemoteSubwayDataSourceImpl.kt
  core/data/src/main/java/com/moya/funch/di/DataSourcesModule.kt
  core/data/src/main/java/com/moya/funch/mapper/SubwayStationMapper.kt
  core/data/src/main/java/com/moya/funch/repository/SubwayRepositoryImpl.kt
  core/domain/src/main/java/com/moya/funch/repository/SubwayRepository.kt
  core/domain/src/main/java/com/moya/funch/usecase/LoadSubwayStationsUseCase.kt
  core/network/src/main/java/com/moya/funch/network/di/ServiceModule.kt
  core/network/src/main/java/com/moya/funch/network/dto/response/subwaystation/LocationResponse.kt
  core/network/src/main/java/com/moya/funch/network/dto/response/subwaystation/SubwayStationsResponse.kt
  core/network/src/main/java/com/moya/funch/network/service/SubwayService.kt
  core/network/src/test/java/com/moya/funch/network/service/SubwayServiceTest.kt
  core/network/src/test/res/search_subway_stations_result.json
Labels: ham😸

#75 [Feat] 지하철 검색 UI 제작 및 기능 구현
  core/data/src/main/java/com/moya/funch/repository/SubwayRepositoryImpl.kt
  core/designsystem/src/main/java/com/moya/funch/component/TextField.kt
  core/designsystem/src/main/java/com/moya/funch/ui/FunchCaption.kt
  feature/profile/src/main/java/com/moya/funch/CreatePofileViewModel.kt
  feature/profile/src/main/java/com/moya/funch/CreateProflieScreen.kt
  feature/profile/src/main/java/com/moya/funch/uimodel/ProfileUiModel.kt
Labels: ham😸

#77 [Feat] splash screen
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/moya/funch/MainActivity.kt
  app/src/main/java/com/moya/funch/splash/SplashScreen.kt
  app/src/main/res/drawable/ic_splash_bg_bottom.xml
  app/src/main/res/drawable/ic_splash_bg_top.xml
  app/src/main/res/drawable/ic_splash_logo.xml
  app/src/main/res/raw/funch_splash_background.json
  app/src/main/res/raw/funch_splash_icon_lottie.json
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/ic_funch_logo_background.xml
  app/src/main/res/values/splash.xml
  app/src/main/res/values/themes.xml
  feature/onboarding/src/main/java/com/moya/funch/onboarding/OnBoardingScreen.kt
Labels: june🙇‍♂️

#73 [feat] Match Recommend, profile UI 구현
  core/data/src/main/java/com/moya/funch/mapper/MatchingMapper.kt
  core/domain/src/main/java/com/moya/funch/entity/match/MatchInfo.kt
  core/domain/src/main/java/com/moya/funch/entity/match/Matching.kt
  core/network/src/main/java/com/moya/funch/network/dto/response/match/MatchInfoResponse.kt
  core/network/src/main/java/com/moya/funch/network/dto/response/match/MatchingResponse.kt
  core/network/src/main/java/com/moya/funch/network/dto/response/match/ProfileResponse.kt
  core/network/src/test/java/com/moya/funch/network/service/MatchingServiceTest.kt
  core/network/src/test/res/matching_result.json
  feature/home/src/main/java/com/moya/funch/HomeScreen.kt
  feature/home/src/main/java/com/moya/funch/HomeViewModel.kt
  feature/match/src/main/java/com/moya/funch/match/MatchScreen.kt
  feature/match/src/main/java/com/moya/funch/match/MatchViewModel.kt
  feature/match/src/main/java/com/moya/funch/match/component/MatchCardLayout.kt
  feature/match/src/main/java/com/moya/funch/match/component/MatchHorizontalPager.kt
  feature/match/src/main/java/com/moya/funch/match/component/MatchProfileCard.kt
  feature/match/src/main/java/com/moya/funch/match/component/RecommendCard.kt
  feature/match/src/main/java/com/moya/funch/match/component/SimilarityCard.kt
  feature/match/src/main/java/com/moya/funch/match/model/MatchProfileUiModel.kt
  feature/match/src/main/res/values/strings.xml
Labels: june🙇‍♂️

#81 [Feat] Home - viewCount 업데이트
  feature/home/src/main/java/com/moya/funch/HomeScreen.kt
  feature/home/src/main/java/com/moya/funch/HomeViewModel.kt
Labels: june🙇‍♂️

#83 [Feat] 온보딩 화면 연결 및 UX 개선
  app/build.gradle.kts
  app/src/main/java/com/moya/funch/MainActivity.kt
  app/src/main/java/com/moya/funch/navigation/FunchNavHost.kt
  app/src/main/java/com/moya/funch/ui/FunchApp.kt
  core/designsystem/src/main/java/com/moya/funch/component/Chip.kt
  core/designsystem/src/main/java/com/moya/funch/theme/Theme.kt
  feature/home/src/main/java/com/moya/funch/navigation/HomeNavigation.kt
  feature/onboarding/src/main/java/com/moya/funch/onboarding/navigation/OnBoardingNavigation.kt
  feature/profile/src/main/java/com/moya/funch/CreatePofileViewModel.kt
  feature/profile/src/main/java/com/moya/funch/CreateProflieScreen.kt
  feature/profile/src/main/java/com/moya/funch/navigation/MyProfileNavigatoin.kt
Labels: ham😸

#85 [Release] 1.0.0 배포 - develop
  .github/workflows/PR_Builder.yml
  app/build.gradle.kts
Labels: june🙇‍♂️, ham😸

#91 [QA] View Count 2씩 올라가는 버그 방지, 화면 회전 방지
  app/src/main/AndroidManifest.xml
  core/data/src/main/java/com/moya/funch/datasource/remote/RemoteMatchDataSource.kt
  core/data/src/main/java/com/moya/funch/datasource/remote/RemoteMatchDataSourceImpl.kt
  core/data/src/main/java/com/moya/funch/repository/MatchingRepositoryImpl.kt
  core/domain/src/main/java/com/moya/funch/repository/MatchingRepository.kt
  core/domain/src/main/java/com/moya/funch/usecase/CanMatchProfileUseCase.kt
  core/network/src/main/java/com/moya/funch/network/dto/response/match/CanMatchResponse.kt
  core/network/src/main/java/com/moya/funch/network/service/MatchingService.kt
  core/network/src/test/java/com/moya/funch/network/service/MatchingServiceTest.kt
  core/network/src/test/res/can_matching_fail.json
  core/network/src/test/res/can_matching_success.json
Labels: june🙇‍♂️, QA

#97 [Fix] 릴리즈 v1.0.0 1차 QA
  app/src/main/java/com/moya/funch/di/MemberModule.kt
  app/src/main/java/com/moya/funch/navigation/FunchNavHost.kt
  core/data/src/main/java/com/moya/funch/datasource/remote/RemoteUserDataSource.kt
  core/data/src/main/java/com/moya/funch/datasource/remote/RemoteUserDataSourceImpl.kt
  core/data/src/main/java/com/moya/funch/repository/MemberRepositoryImpl.kt
  core/designsystem/src/main/java/com/moya/funch/ui/FunchDialog.kt
  core/domain/src/main/java/com/moya/funch/repository/MemberRepository.kt
  core/domain/src/main/java/com/moya/funch/usecase/DeleteUserProfileUseCase.kt
  core/network/src/main/java/com/moya/funch/network/service/MemberService.kt
  feature/profile/src/main/java/com/moya/funch/CreateProflieScreen.kt
  feature/profile/src/main/java/com/moya/funch/MyProfileScreen.kt
  feature/profile/src/main/java/com/moya/funch/MyProfileViewModel.kt
  feature/profile/src/main/java/com/moya/funch/navigation/MyProfileNavigatoin.kt
  feature/profile/src/main/res/values/strings.xml
Labels: ham😸, QA, Fix

#99 [Release] 1.1.0 버전 업데이트 - master
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/moya/funch/di/MemberModule.kt
  app/src/main/java/com/moya/funch/navigation/FunchNavHost.kt
  core/data/src/main/java/com/moya/funch/datasource/remote/RemoteMatchDataSource.kt
  core/data/src/main/java/com/moya/funch/datasource/remote/RemoteMatchDataSourceImpl.kt
  core/data/src/main/java/com/moya/funch/datasource/remote/RemoteUserDataSource.kt
  core/data/src/main/java/com/moya/funch/datasource/remote/RemoteUserDataSourceImpl.kt
  core/data/src/main/java/com/moya/funch/repository/MatchingRepositoryImpl.kt
  core/data/src/main/java/com/moya/funch/repository/MemberRepositoryImpl.kt
  core/designsystem/src/main/java/com/moya/funch/ui/FunchDialog.kt
  core/domain/src/main/java/com/moya/funch/repository/MatchingRepository.kt
  core/domain/src/main/java/com/moya/funch/repository/MemberRepository.kt
  core/domain/src/main/java/com/moya/funch/usecase/CanMatchProfileUseCase.kt
  core/domain/src/main/java/com/moya/funch/usecase/DeleteUserProfileUseCase.kt
  core/network/src/main/java/com/moya/funch/network/dto/response/match/CanMatchResponse.kt
  core/network/src/main/java/com/moya/funch/network/service/MatchingService.kt
  core/network/src/main/java/com/moya/funch/network/service/MemberService.kt
  core/network/src/test/java/com/moya/funch/network/service/MatchingServiceTest.kt
  core/network/src/test/res/can_matching_fail.json
  core/network/src/test/res/can_matching_success.json
  feature/profile/src/main/java/com/moya/funch/CreateProflieScreen.kt
  feature/profile/src/main/java/com/moya/funch/MyProfileScreen.kt
  feature/profile/src/main/java/com/moya/funch/MyProfileViewModel.kt
  feature/profile/src/main/java/com/moya/funch/navigation/MyProfileNavigatoin.kt
  feature/profile/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: ham😸

#98 [Release] 1.1.0 버전 업데이트 - develop
  app/src/main/java/com/moya/funch/navigation/FunchNavHost.kt
  feature/profile/src/main/java/com/moya/funch/navigation/MyProfileNavigatoin.kt
  gradle/libs.versions.toml
Labels: ham😸

#100 [QA] 스플래쉬 UI 수정
  app/src/main/java/com/moya/funch/MainActivity.kt
  app/src/main/java/com/moya/funch/splash/SplashScreen.kt
  app/src/main/res/raw/funch_splash_icon_lottie.json
Labels: QA, Fix

#113 [Fix] 프로필 생성 페이지 QA 작업
  core/designsystem/src/main/java/com/moya/funch/ui/FunchCaption.kt
  core/designsystem/src/main/java/com/moya/funch/ui/FunchDropDown.kt
  feature/profile/src/main/java/com/moya/funch/CreatePofileViewModel.kt
  feature/profile/src/main/java/com/moya/funch/CreateProflieScreen.kt
Labels: ham😸, Fix
